Repository Konkuk-JJabaries/Product, pull requests merged in 2020-01, with the labels that each got.

#3 interface 추가
  .prettierrc
  Common/action/index.ts
  Common/action/product_detail/ProductDetailRequest.interface.ts
  Common/action/product_detail/ProductDetailResponse.interface.ts
  Common/action/product_detail/index.ts
  Common/action/product_list/ProductListRequest.interface.ts
  Common/action/product_list/ProductListResponse.interface.ts
  Common/action/product_list/index.ts
  Common/category/Category.type.ts
  Common/category/child_category/BabyBirth.type.ts
  Common/category/child_category/BookRecordDVD.type.ts
  Common/category/child_category/Car.type.ts
  Common/category/child_category/Clothes.type.ts
  Common/category/child_category/Cosmetics.type.ts
  Common/category/child_category/Electronics.type.ts
  Common/category/child_category/FurnitureInteriors.type.ts
  Common/category/child_category/GeneralMerchandise.type.ts
  Common/category/child_category/LifeCulture.type.ts
  Common/category/child_category/OverseasLuxury.type.ts
  Common/category/child_category/SportsLeisure.type.ts
  Common/category/child_category/ToysPhrasesHobbies.type.ts
  Common/category/child_category/TravelCulture.type.ts
  Common/category/child_category/index.ts
  Common/index.ts
  Common/site_code/SiteCode.type.ts
  Common/site_code/index.ts
Labels: 기능 추가

#8 init setting
  API/README.md
Labels: 기능 추가, 기타

#11 API 팀용 내용 업데이트
  API/README.md
  API/a000/Common/README.md
  API/a000/Common/action/check_link/CheckLinkResponse.interface.ts
  API/a000/Common/action/check_link/index.ts
  API/a000/Common/action/index.ts
  API/a000/Common/action/product_detail/ProductDetailResponse.interface.ts
  API/a000/Common/action/product_detail/ProductDetailTags.interface.ts
  API/a000/Common/action/product_detail/index.ts
  API/a000/Common/action/product_list/ProductListRequest.interface.ts
  API/a000/Common/action/product_list/ProductListResponse.interface.ts
  API/a000/Common/site_code/SiteCode.type.ts
  API/a000/check_link/index.ts
  API/a000/check_link/src/request.service.ts
  API/a000/interfaces/SiteRequest.interface.ts
  API/a000/interfaces/SiteResponse.interface.ts
  API/a000/product_list/index.ts
  API/a000/product_list/product_list.e2e.ts
  API/a000/product_list/src/request.service.ts
  API/a000/product_list/src/responseMapping.ts
  API/a000/product_list/src/scrap.component.ts
  API/a000/product_list/test/product_list.test.ts
  API/package-lock.json
  API/package.json
  API/tsconfig.json
  Common/README.md
  Common/action/check_link/CheckLinkResponse.interface.ts
  Common/action/check_link/index.ts
  Common/action/index.ts
  Common/index.ts
Labels: 기능 추가, 문서화
